### ISSUE TITLE
Session doesn't clear for subroutes

### ISSUE THREAD

**Issue by ahvin2020** [haruyama/golang-goji-sample#11]
1. In server.go, I created this routes
```javascript
goji.Get("/apitest", application.Route(controller, "apitest"))
goji.Get("/api/test", application.Route(controller, "apitest"))
```

Both of them just prints out the value of **session.Values["UserId"]**

2. I log in, so that **session.Values["UserId"]** has a value.
3. I visit both **/apitest** and **/api/test**, and they print out value of **session.Values["UserId"]** fine
3. Then I log out, so that **session.Values["UserId"]** is set to nil
4. I visit both **/apitest** and **/api/test**, **/apitest** will now print out nil; **api/test** still print the value of **session.Values["UserId"]**

What did I do wrong here?

**Comment by haruyama** [comment]
This is because CookieStore.Path is not setted explicitly.

At #12, I set CookieStore.Path to '/'.

In our real project, We met same problem, but I forget backporting this problem.

Thank you.

**Comment by ahvin2020** [comment]
Ah, you are right! That solved the problem. Closing this issue now.
