### ISSUE TITLE
Clearing gorilla session

### ISSUE THREAD

**Issue by aymer** [haruyama/golang-goji-sample#7]
Hi,

I must be missing something, but just wondering how are you clearing the gorilla session in these sample project? As per their doc http://www.gorillatoolkit.org/pkg/sessions
> Important Note: If you aren't using gorilla/mux, you need to wrap your handlers with context.ClearHandler as or else you will leak memory! An easy way to do this is to wrap the top-level mux when calling http.ListenAndServe: "

So aren't we supposed to clear them somehow? 
Thanks

**Comment by haruyama** [comment]
See #2.

https://github.com/haruyama/golang-goji-sample/blob/master/server.go#L43
